name: Redeploy Site
on:
  workflow_dispatch:

jobs:
  Redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Frontend ğŸ—
        run: |
          cp -r ./{output,data,config,sourcecred.json,package.json,yarn.lock,cache,.gitignore} ./site/
      
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: site
